version: '3'

services:
  tictactoe-app:
    build:
      context: ./app
    ports:
      - 80:8080
    volumes:
      - tictactoe-data:/app/tictactoe

volumes:
  tictactoe-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /app/tictactoe
