---
server:
  port: 8080

spring:
  application:
    name: tictactoe-service
  jpa:    hibernate:      ddl-auto: update    generate-ddl: true 
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:    url: jdbc:h2:file:/app/tictactoe/data/tictactoe_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:    console:
      path: /h2      enabled: true 
      
logging:  file:    name: /app/tictactoe/logs/application.log
  pattern:    file: "%d %p %c{1.} [%t] %m%n"  level: 
    org.springframework: ERROR
    com.wipro: DEBUG    